### ISSUE TITLE
Not working at all on MacOS 11.6

### ISSUE THREAD

**Issue by alonsourbano** [PierreJanineh/MaciCloudAutomators#1]
This doesn't work on MacOS 11.6, even if followed all the steps mentioned:

- "Install" all apps on the same directory, I assumed this just meant `git clone`. Anyway all the apps are on the same directory.
- Open "all four" applications on Automator and save them. There is actually seven applications, I did it for all seven but nothing happens.
- Check the Security & Privacy settings.

When I run the iCloud tool app it complains that "The file does not contain a valid workflow document."

**Comment by PierreJanineh** [comment]
When you open the `iCloud Tool.app` in Automator, you need to find 2 AppleScript actions.
(As shown in the screenshot below):
![image](https://user-images.githubusercontent.com/21991920/138589379-a86edfa2-e15e-4f3e-80e4-a61ad15bde50.jpeg)

-In case you don't, you probably need to re-clone the repository.
-If you do find 2 AppleScript actions, try Running the workflow from within the Automator app. Try following the Log to find out the issue.

The whole bundle should work on MacOS 11.6 with no issues.
